"use client";

import * as React from "react";
import { Plus, ShieldCheck, Terminal } from "lucide-react";
import { listCliRunners, listMcpServers, saveCliRunner, saveMcpServer, setMcpGrant } from "@/lib/actions/phase7";
import { listMarcoAgents } from "@/lib/actions/marco";
import type { MarcoAgent } from "@/lib/marco-types";

type Server = { id: string; name: string; url: string; status: string; enabled: boolean; agent_mcp_grants?: { agent_id: string; can_read: boolean; can_write: boolean }[] };
type Runner = { id: string; name: string; kind: string; status: string; enabled: boolean };

export function ConnectionsPanel() {
  const [servers, setServers] = React.useState<Server[]>([]), [runners, setRunners] = React.useState<Runner[]>([]), [agents, setAgents] = React.useState<MarcoAgent[]>([]), [serverName, setServerName] = React.useState(""), [serverUrl, setServerUrl] = React.useState(""), [runnerName, setRunnerName] = React.useState(""), [runnerKind, setRunnerKind] = React.useState("codex"), [error, setError] = React.useState<string | null>(null);
  const refresh = React.useCallback(async () => { const [nextServers, nextRunners, nextAgents] = await Promise.all([listMcpServers(), listCliRunners(), listMarcoAgents()]); setServers(nextServers as Server[]); setRunners(nextRunners as Runner[]); setAgents(nextAgents); }, []);
  React.useEffect(() => { void refresh().catch(() => setError("Connections could not be loaded.")); }, [refresh]);
  async function addServer(event: React.FormEvent) { event.preventDefault(); if (!serverName.trim() || !serverUrl.trim()) return; try { await saveMcpServer({ name: serverName, url: serverUrl, transport: "http" }); setServerName(""); setServerUrl(""); await refresh(); } catch { setError("The server record could not be saved."); } }
  async function addRunner(event: React.FormEvent) { event.preventDefault(); if (!runnerName.trim()) return; try { await saveCliRunner({ name: runnerName, kind: runnerKind, enabled: false }); setRunnerName(""); await refresh(); } catch { setError("The runner record could not be saved."); } }
  return <div className="marco-connections"><section className="marco-phase7-panel"><header><div><small>Scoped tools</small><h2>MCP servers</h2><p>Tool permissions are granted per agent. Write access stays off until you explicitly allow it.</p></div></header><form className="marco-inline-form" onSubmit={addServer}><input value={serverName} onChange={(event) => setServerName(event.target.value)} placeholder="Server name" required /><input value={serverUrl} onChange={(event) => setServerUrl(event.target.value)} placeholder="https://server.example/mcp" type="url" required /><button><Plus size={14} /> Add server</button></form>{servers.map((server) => <article className="marco-connection-row" key={server.id}><div><b>{server.name}</b><small>{server.url} · {server.status}</small></div><details><summary>Agent grants</summary>{agents.map((agent) => { const grant = server.agent_mcp_grants?.find((item) => item.agent_id === agent.id); return <label key={agent.id}><input type="checkbox" checked={Boolean(grant?.can_read)} onChange={(event) => void setMcpGrant({ agentId: agent.id, serverId: server.id, canRead: event.target.checked, canWrite: false }).then(refresh)} />{agent.name}</label>; })}</details></article>)}{!servers.length && <div className="marco-phase7-empty"><ShieldCheck size={18} /><b>No MCP servers</b><p>Add a server record before granting tools to an agent.</p></div>}</section><section className="marco-phase7-panel"><header><div><small>Worker sandbox only</small><h2>CLI runners</h2><p>Runner records do not run commands on this machine. Each command is authorized and logged in the worker.</p></div></header><form className="marco-inline-form" onSubmit={addRunner}><input value={runnerName} onChange={(event) => setRunnerName(event.target.value)} placeholder="Runner name" required /><select value={runnerKind} onChange={(event) => setRunnerKind(event.target.value)}><option value="claude_code">Claude Code</option><option value="codex">Codex</option><option value="github">GitHub</option><option value="vercel">Vercel</option></select><button><Plus size={14} /> Add runner</button></form>{runners.map((runner) => <article className="marco-connection-row" key={runner.id}><Terminal size={16} /><div><b>{runner.name}</b><small>{runner.kind} · {runner.status}</small></div><span>{runner.enabled ? "Enabled" : "Disabled"}</span></article>)}{!runners.length && <div className="marco-phase7-empty"><Terminal size={18} /><b>No CLI runners</b><p>Runners become available only from the configured worker sandbox.</p></div>}</section>{error && <p className="marco-phase7-error">{error}</p>}</div>;
}
