"use client";

import * as React from "react";
import { Check, FileText, Plus, Power, Sparkles } from "lucide-react";
import { importSkillFromText, listSkills, setAgentSkill, setSkillStatus } from "@/lib/actions/phase7";
import { listMarcoAgents } from "@/lib/actions/marco";
import type { MarcoAgent } from "@/lib/marco-types";

type Skill = { id: string; name: string; description: string | null; source: string; status: "draft" | "installed" | "disabled"; triggers: string[]; agent_skills?: { agent_id: string; enabled: boolean }[] };

export function SkillsPanel() {
  const [skills, setSkills] = React.useState<Skill[]>([]), [agents, setAgents] = React.useState<MarcoAgent[]>([]), [open, setOpen] = React.useState(false), [name, setName] = React.useState(""), [markdown, setMarkdown] = React.useState(""), [selected, setSelected] = React.useState<string[]>([]), [busy, setBusy] = React.useState(false), [error, setError] = React.useState<string | null>(null);
  const refresh = React.useCallback(async () => { const [nextSkills, nextAgents] = await Promise.all([listSkills(), listMarcoAgents()]); setSkills(nextSkills as Skill[]); setAgents(nextAgents); }, []);
  React.useEffect(() => { void refresh().catch(() => setError("Skills could not be loaded.")); }, [refresh]);
  async function create() { if (!name.trim() || !markdown.trim()) return; setBusy(true); setError(null); try { await importSkillFromText({ name, markdown, agentIds: selected }); setName(""); setMarkdown(""); setSelected([]); setOpen(false); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Skill import failed."); } finally { setBusy(false); } }
  return <section className="marco-phase7-panel"><header><div><small>Reusable capability</small><h2>Skills</h2><p>Instructions are attached to selected agents. Helper files are stored, never executed during import.</p></div><button type="button" onClick={() => setOpen((value) => !value)}><Plus size={15} /> Build skill</button></header>{error && <p className="marco-phase7-error">{error}</p>}{open && <form onSubmit={(event) => { event.preventDefault(); void create(); }} className="marco-skill-builder"><label>Name<input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Product brief reviewer" /></label><label>SKILL.md or markdown<textarea required value={markdown} onChange={(event) => setMarkdown(event.target.value)} placeholder={'---\nname: Product brief reviewer\ntriggers: brief, review\n---\n# Product brief reviewer\n...'} /></label><fieldset><legend>Enable for agents</legend><div>{agents.map((agent) => <label key={agent.id}><input type="checkbox" checked={selected.includes(agent.id)} onChange={() => setSelected((current) => current.includes(agent.id) ? current.filter((id) => id !== agent.id) : [...current, agent.id])} />{agent.name}</label>)}</div></fieldset><footer><button type="submit" disabled={busy}>{busy ? "Saving…" : "Save draft"}</button><span>Review and install before it can run.</span></footer></form>}<div className="marco-skill-list">{skills.length ? skills.map((skill) => <article key={skill.id}><div className="marco-skill-icon"><FileText size={16} /></div><div><b>{skill.name}</b><p>{skill.description ?? "No description"}</p><small>{skill.source.replace("_", " ")} · {skill.triggers?.length ? skill.triggers.join(", ") : "No trigger filter"}</small></div><div className="marco-skill-actions"><span className={`is-${skill.status}`}>{skill.status}</span>{skill.status === "draft" && <button type="button" onClick={() => void setSkillStatus(skill.id, "installed").then(refresh)}><Check size={13} /> Install</button>}{skill.status === "installed" && <button type="button" onClick={() => void setSkillStatus(skill.id, "disabled").then(refresh)}><Power size={13} /> Disable</button>}<details><summary>Agents</summary>{agents.map((agent) => { const grant = skill.agent_skills?.find((item) => item.agent_id === agent.id); return <label key={agent.id}><input type="checkbox" checked={Boolean(grant?.enabled)} onChange={(event) => void setAgentSkill({ agentId: agent.id, skillId: skill.id, enabled: event.target.checked }).then(refresh)} />{agent.name}</label>; })}</details></div></article>) : <div className="marco-phase7-empty"><Sparkles size={18} /><b>No skills installed</b><p>Build a draft from a thread or import a recognized skill file.</p></div>}</div></section>;
}
