import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { ApprovalResolution, LaneStatus, RuntimeDispatch, RuntimeLane } from "./types";
type Row = Record<string, unknown>;
let client: SupabaseClient | null = null;

/** Runtime access is service-role only. A browser or publishable key cannot execute turns. */
export function runtimeDb() {
  if (client) return client;
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error("The MARCO runtime requires NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.");
  client = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
  return client;
}
function fail(error: { message: string } | null) { if (error) throw new Error(error.message); }
export function row<T extends Row>(value: unknown) { return value as T; }
export async function audit(input: { agentId?: string | null; runId?: string | null; action: string; target?: string | null; decision?: string | null; detail?: Record<string, unknown> }) { const { error } = await runtimeDb().from("audit_log").insert({ agent_id: input.agentId ?? null, run_id: input.runId ?? null, action: input.action, target: input.target ?? null, decision: input.decision ?? null, detail: input.detail ?? {} }); fail(error); }
export async function queueTurn(input: RuntimeDispatch) { const db = runtimeDb(); const { data, error } = await db.from("runs_lanes").insert({ run_id: input.runId, agent_id: input.agentId, thread_id: input.threadId, lane: input.lane, request: input.request, source_message_id: input.sourceMessageId ?? null, status: "queued" }).select("*").single(); fail(error); await audit({ agentId: input.agentId, runId: input.runId, action: "queue", target: input.lane, decision: "queued" }); return row<Row>(data); }
const laneOrder: RuntimeLane[] = ["user", "agent", "automation", "background"];
export async function claimNextTurn(workerId: string) { const db = runtimeDb(); for (const lane of laneOrder) { const { data, error } = await db.from("runs_lanes").select("*").eq("lane", lane).eq("status", "queued").order("created_at").limit(1).maybeSingle(); fail(error); if (!data) continue; const { data: claimed, error: claimError } = await db.from("runs_lanes").update({ status: "running", started_at: new Date().toISOString(), worker_id: workerId }).eq("id", data.id).eq("status", "queued").select("*").maybeSingle(); fail(claimError); if (claimed) return row<Row>(claimed); } return null; }
export async function setLaneStatus(id: string, status: LaneStatus, detail: { interruptReason?: string; error?: string } = {}) { const update: Row = { status }; if (["done", "failed", "cancelled"].includes(status)) update.ended_at = new Date().toISOString(); if (detail.interruptReason) update.interrupt_reason = detail.interruptReason; if (detail.error) update.error = detail.error; const { error } = await runtimeDb().from("runs_lanes").update(update).eq("id", id); fail(error); }
export async function getTurn(runId: string) { const { data, error } = await runtimeDb().from("runs").select("*").eq("id", runId).single(); fail(error); return row<Row>(data); }
export async function getAgent(agentId: string) { const { data, error } = await runtimeDb().from("agents").select("*").eq("id", agentId).single(); fail(error); return row<Row>(data); }
export async function appendMessage(input: { threadId: string; agentId: string; runId?: string; role: string; body: string; kind?: string; payload?: Row }) { const db = runtimeDb(); const { data, error } = await db.from("messages").insert({ thread_id: input.threadId, agent_id: input.agentId, run_id: input.runId ?? null, role: input.role, kind: input.kind ?? "text", body: input.body, payload: input.payload ?? null }).select("*").single(); fail(error); await db.from("threads").update({ last_message_preview: input.body.slice(0, 140), updated_at: new Date().toISOString(), unread: input.role === "agent" }).eq("id", input.threadId); return row<Row>(data); }
export async function saveContext(runId: string, context: unknown) { const db = runtimeDb(); const run = await getTurn(runId); const inputs = (run.inputs as Row | null) ?? {}; const { error } = await db.from("runs").update({ inputs: { ...inputs, runtime_context: context }, status: "running" }).eq("id", runId); fail(error); }
export async function completeRun(runId: string, output: string, cost: number | null) { const db = runtimeDb(); const run = await getTurn(runId); const steps = Array.isArray(run.steps) ? run.steps : []; const { error } = await db.from("runs").update({ status: "completed", cost: cost ?? run.cost ?? 0, steps: [...steps, { kind: "runtime_output", at: new Date().toISOString(), detail: output.slice(0, 600) }] }).eq("id", runId); fail(error); }
export async function failRun(runId: string, reason: string) { const { error } = await runtimeDb().from("runs").update({ status: "failed", steps: [{ kind: "runtime_error", at: new Date().toISOString(), detail: reason }] }).eq("id", runId); fail(error); }
export async function createApproval(input: { runId: string; agentId: string; action: string; target?: string; detail?: Row }) { const db = runtimeDb(); const expiresAt = new Date(Date.now() + 10 * 60_000).toISOString(); const { data, error } = await db.from("approval_requests").insert({ run_id: input.runId, agent_id: input.agentId, action: input.action, target: input.target ?? null, detail: input.detail ?? {}, expires_at: expiresAt }).select("*").single(); fail(error); await db.from("runs").update({ status: "needs_approval", approval_state: "pending" }).eq("id", input.runId); await audit({ agentId: input.agentId, runId: input.runId, action: input.action, target: input.target, decision: "ask", detail: { approval_id: data.id } }); return row<Row>(data); }
export async function resolveApproval(id: string, resolution: ApprovalResolution) { const db = runtimeDb(); const now = new Date().toISOString(); const { data, error } = await db.from("approval_requests").update({ resolution, resolved_at: now }).eq("id", id).is("resolved_at", null).gt("expires_at", now).select("*").maybeSingle(); fail(error); if (!data) return null; await audit({ agentId: data.agent_id, runId: data.run_id, action: data.action, target: data.target, decision: resolution, detail: row<Row>(data.detail ?? {}) }); if (resolution === "always" || resolution === "never") { const agent = await getAgent(String(data.agent_id)); const permissions = row<Row>(agent.permissions ?? {}); const { error: agentError } = await db.from("agents").update({ permissions: { ...permissions, [data.action]: resolution } }).eq("id", data.agent_id); fail(agentError); } if (resolution === "allow_once" || resolution === "always") { const { error: laneError } = await db.from("runs_lanes").update({ status: "queued", started_at: null }).eq("run_id", data.run_id).eq("status", "paused"); fail(laneError); await db.from("runs").update({ status: "running", approval_state: resolution }).eq("id", data.run_id); } else { await db.from("runs_lanes").update({ status: "cancelled", ended_at: now, interrupt_reason: "permission_denied" }).eq("run_id", data.run_id).eq("status", "paused"); await db.from("runs").update({ status: "cancelled", approval_state: resolution }).eq("id", data.run_id); } return row<Row>(data); }
export async function cancelRun(runId: string) { const db = runtimeDb(); const now = new Date().toISOString(); const { error } = await db.from("runs_lanes").update({ status: "cancelled", ended_at: now, interrupt_reason: "cancelled_by_user" }).eq("run_id", runId).in("status", ["queued", "paused"]); fail(error); await db.from("runs").update({ status: "cancelled" }).eq("id", runId); }
