import { runtimeDb, row } from "../lib/runtime/repository";
import type { ContextEnvelope, PermissionMode } from "../lib/runtime/types";
const MAX_MEMORY_CHARS = 2_400;
const precedence = ["Platform safety and legal policy", "Current user instruction", "Approved brand rules", "Agent instructions", "Locked artifact constraints", "Current brief", "Unapproved suggestions"] as const;
export async function buildContext(input: { agentId: string; brandId: string | null; threadId: string; runId: string; request: string }): Promise<ContextEnvelope> {
  const db = runtimeDb();
  const [{ data: agent, error: agentError }, { data: run, error: runError }, { data: messages, error: messageError }, { data: brand, error: brandError }] = await Promise.all([db.from("agents").select("id,name,tagline,instructions,permissions,can_handoff_to").eq("id", input.agentId).single(), db.from("runs").select("inputs,asset_manifest").eq("id", input.runId).single(), db.from("messages").select("role,body,created_at").eq("thread_id", input.threadId).eq("agent_id", input.agentId).order("created_at", { ascending: false }).limit(12), input.brandId ? db.from("brands").select("id,name,colors,voice,audience,offers,restrictions").eq("id", input.brandId).maybeSingle() : Promise.resolve({ data: null, error: null })]);
  if (agentError || runError || messageError || brandError) throw new Error(agentError?.message ?? runError?.message ?? messageError?.message ?? brandError?.message ?? "Unable to assemble context.");
  const memoryQuery = await db.from("memory_facts").select("id,text,tier,scope,scope_id,learned_at").eq("active", true).in("scope", input.brandId ? ["agent", "brand", "global"] : ["agent", "global"]).order("learned_at", { ascending: false }).limit(60); if (memoryQuery.error) throw new Error(memoryQuery.error.message);
  let used = 0; const memory = (memoryQuery.data ?? []).filter((fact) => fact.scope === "global" || (fact.scope === "agent" && fact.scope_id === input.agentId) || (fact.scope === "brand" && fact.scope_id === input.brandId)).filter((fact) => { const size = String(fact.text).length; if (used + size > MAX_MEMORY_CHARS || fact.tier === "note") return false; used += size; return true; }).map((fact) => ({ id: String(fact.id), text: String(fact.text), tier: fact.tier as "profile" | "log" | "note", scope: String(fact.scope) }));
  if (memory.length) await db.from("memory_facts").update({ last_used_at: new Date().toISOString() }).in("id", memory.map((fact) => fact.id));
  const handoffIds = Array.isArray(agent.can_handoff_to) ? agent.can_handoff_to : []; const { data: roster, error: rosterError } = handoffIds.length ? await db.from("agents").select("id,name,tagline").in("id", handoffIds) : { data: [], error: null }; if (rosterError) throw new Error(rosterError.message);
  const permissions = row<Record<string, unknown>>(agent.permissions ?? {}); const actions = ["generate", "publish", "write_knowledge", "mcp_write", "use_cli"];
  return { identity: { id: String(agent.id), name: String(agent.name), tagline: agent.tagline as string | null, instructions: agent.instructions as string | null }, brand: brand ? row<Record<string, unknown>>(brand) : null, brief: row<Record<string, unknown>>(run.inputs ?? {}), recent_chat: (messages ?? []).reverse().map((message) => ({ role: String(message.role), body: message.body as string | null, created_at: String(message.created_at) })), memory, manifest: Array.isArray(run.asset_manifest) ? run.asset_manifest : [], roster: (roster ?? []).map((item) => ({ id: String(item.id), name: String(item.name), tagline: item.tagline as string | null })), tools: actions.map((action) => ({ action, mode: (permissions[action] === "always" || permissions[action] === "never" ? permissions[action] : "ask") as PermissionMode })), request: input.request, precedence };
}
